 Raw Data Problems : --> 1. Missing vals , 2. Duplicate val , 3. Spelling Mistake , 4. Ouliers , 5. Incorrect datatypes , 6. Incorrect formatting

Data Cleaning :--> detecting , processing and handling missing values , outliers and duplicates

# Data Collection and Inspection (Summary,distribution plot,info,frequency,visual inspect)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('data.csv', encoding='latin1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [6]:
df.isnull().sum()/len(df)*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

CustomerID has so much missing vals .. 
dont drop na

In [7]:
df[df.duplicated()].shape

(5268, 8)

In [8]:
df['CustomerID'].value_counts().head(10)

CustomerID
17841.0    7983
14911.0    5903
14096.0    5128
12748.0    4642
14606.0    2782
15311.0    2491
14646.0    2085
13089.0    1857
13263.0    1677
14298.0    1640
Name: count, dtype: int64

In [9]:
df[df['CustomerID']==17841.0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,12/1/2010 14:30,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,12/1/2010 14:30,0.85,17841.0,United Kingdom
2037,536557,21495,SKULLS AND CROSSBONES WRAP,25,12/1/2010 14:41,0.42,17841.0,United Kingdom
2038,536557,46000R,POLYESTER FILLER PAD 45x30cm,2,12/1/2010 14:41,1.45,17841.0,United Kingdom
2039,536557,46000S,POLYESTER FILLER PAD 40x40cm,1,12/1/2010 14:41,1.45,17841.0,United Kingdom
...,...,...,...,...,...,...,...,...
537749,581334,23399,HOME SWEET HOME HANGING HEART,3,12/8/2011 12:07,0.85,17841.0,United Kingdom
537750,581334,22893,MINI CAKE STAND T-LIGHT HOLDER,12,12/8/2011 12:07,0.42,17841.0,United Kingdom
537751,581334,22371,AIRLINE BAG VINTAGE TOKYO 78,1,12/8/2011 12:07,4.25,17841.0,United Kingdom
537752,581334,22309,TEA COSY RED STRIPE,1,12/8/2011 12:07,2.55,17841.0,United Kingdom
537753,581334,21926,RED/CREAM STRIPE CUSHION COVER,8,12/8/2011 12:07,1.25,17841.0,United Kingdom

In [12]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(col)
        print(df[col].value_counts())
        print('-'*50)

 Handling the missing vals : 1.Delete Rows/Cols(when more than 50 % data missing).. , 2.Imputation (filling missing vals)--> mean , median , mode .. 3.Forward fill / Backward fill (Look forward data and backward data) ... 4. Predictive Imputation (using ml model )...

In [13]:
df.dropna(subset=['CustomerID'], inplace=True)

In [14]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

All Null values removes ..

Handling Duplicates .. 1 . Remove duplicate . 2 . Cheak primary key , 3 . Remove near duplicate records ..

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df['CustomerID'].value_counts()

CustomerID
17841.0    7812
14911.0    5898
14096.0    5128
12748.0    4459
14606.0    2759
           ...
16093.0       1
15313.0       1
15753.0       1
15195.0       1
13747.0       1
Name: count, Length: 4372, dtype: int64

In [17]:
df.drop_duplicates(subset=['CustomerID'],keep='first')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
46,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,12/1/2010 9:00,2.55,13748.0,United Kingdom
65,536374,21258,VICTORIAN SEWING BOX LARGE,32,12/1/2010 9:09,10.95,15100.0,United Kingdom
...,...,...,...,...,...,...,...,...
536969,581233,22178,VICTORIAN GLASS HANGING T-LIGHT,6,12/8/2011 10:33,1.95,13436.0,United Kingdom
537255,581241,22922,FRIDGE MAGNETS US DINER ASSORTED,12,12/8/2011 10:58,0.85,15520.0,United Kingdom
538064,581385,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,24,12/8/2011 13:11,3.75,13298.0,United Kingdom
538812,581416,22466,FAIRY TALE COTTAGE NIGHT LIGHT,1,12/8/2011 14:58,1.95,14569.0,United Kingdom
541768,581578,POST,POSTAGE,3,12/9/2011 12:16,18.00,12713.0,Germany

Correct the Datatypes .. 1. Neumeric --> Int / Float , 2. Categorical --> Object , 3. Date / Time --> datetime

Handling Outliers : 1. Genuine outliers , 2. Errors